# Example search configuration
query: "delivery platforms"
start_year: 2015
end_year: 2023
max_results: 500
fields:
  - title
  - authors
  - year
  - venue
  - abstract
  - url
journals:
  - "Journal of Operations Management"
